name 'sql_helper'
maintainer 'Alex Munoz'
maintainer_email 'amunoz951@gmail.com'
license 'all_rights'
description 'Provides encapsulation for common sql operations'
long_description 'Provides encapsulation for common sql operations'
version '0.2.1'
