name 'sql_helper'
maintainer 'Alex Munoz'
maintainer_email 'amunoz951@gmail.com'
license 'Apache-2.0'
description 'Provides encapsulation for common sql operations'
long_description 'Provides encapsulation for common sql operations'
issues_url 'https://github.com/amunoz951/sql_helper/issues'
source_url 'https://github.com/amunoz951/sql_helper'
chef_version '>= 12'
supports 'windows'
version '0.3.1'
